name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
strategy:
  matrix:
    go: ['1.15', '1.18']
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # baixa os arquivos para a imagem ubuntu-latest
      - uses: actions/setup-go@v2 # prepara o ambiente para rodar o go
        with: 
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go